title:                SCHEF SPORTSWEAR
tagline:              ""
description:          ""
keywords:             ""
url:                  http://xn--e1aa7aos.xn--p1acf
baseurl:              ""
permalink:            pretty

# About/contact
owner:
  name:               Стас Шефер
  phone:              +7 922 14 226 14
  email:              nordy@mail.ru
  vk:                 sportschef

admin:
  name:               Ernest Shefer
  email:              shef-er@ya.ru
  url:                http://shef-er.ru

# Compression
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]

# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:           _sass
  style:              compressed

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
- jekyll-gist
- jekyll-relative-links
