# Permalinks
permalink:            pretty

# Setup
title:                SCHEFER SPORTSWEAR
description:          
tagline:              
url:                  http://xn--e1aa7aos.xn--p1acf
paginate:             4
baseurl:              ""

# Compression
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:           _sass
  style:              compressed

# About/contact
owner:
  name:               Стас Шефер
  phone:              +7 922 14 226 14
  email:              ctac@k66.ru
  vk:                 sportschef

admin:
  name:               Ernest Shefer
  email:              shef-er@ya.ru
  url:                http://shef-er.ru

# Plugins
plugins:
- jekyll-paginate
- jekyll-gist

gems:
  - jekyll-paginate
  - jekyll-gist
