version: '3.9'

services:

  jekyll:
    image: jekyll/jekyll:4.2.0
    command: jekyll serve --watch --force_polling --verbose
    volumes:
      - .:/srv/jekyll
    ports:
      - "4000:4000"
    environment:
      JEKYLL_ENV: development # development / production
