version: "3.8"

networks:
  traefik_proxy:
    external: true

volumes:
  jekyll_site:
    driver: local

services:

  jekyll:
    image: jekyll/jekyll:4.2.0
    container_name: jekyll
    command: jekyll serve
    volumes:
      - ".:/srv/jekyll"
      - "jekyll_site:/srv/jekyll/_site"
    environment:
      JEKYLL_ENV: production # development / production
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      traefik.enable: "true"
      traefik.http.routers.jekyll.rule: "Host(`${INSTANCE_DOMAIN}`)"
      traefik.http.routers.jekyll.entrypoints: "websecure"
      traefik.http.routers.jekyll.tls.certresolver: "letsencrypt"
      traefik.http.routers.jekyll.middlewares: "hsts@file, compress@file"
      traefik.http.services.jekyll.loadbalancer.server.port: "4000"
      traefik.http.routers.jekyll-insecure.rule: "Host(`${INSTANCE_DOMAIN}`)"
      traefik.http.routers.jekyll-insecure.entrypoints: "web"
      traefik.http.routers.jekyll-insecure.middlewares: "redirect@file"
